### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by yiminghe** [ant-design/intl-example#1]
1. zh-cn.js 自动生成

``` js
<FormattedMessage id="title" defaultMessage="中文"/>
```

=>

```
{
 title: "中文"
}
```
1. example 增强

<FormatNumber /> ...

@chrisFan

**Comment by ChrisFan** [comment]
自动生成的脚本好了 [commit](https://github.com/ant-design/intl-example/commit/803516715316b3b493b66807bf8c0c341dafdb71)

文档和例子后面补上

**Comment by yiminghe** [comment]
@ChrisFan  translate.js 封装成单独的 npm 模块吧

**Comment by ChrisFan** [comment]
translate.js 应该是很灵活的，比如有可能这个过程中会掉用一个字典进行自动翻译，也有可能需要生成 json 文件，封装起来的话配置有点复杂。

**Comment by yiminghe** [comment]
调用字典有点扯。。。 里面有变量插值等，肯定是人工翻译

**Comment by ChrisFan** [comment]
金融云就有字典。。并非一个第三方的比如 Google translate 之类的，是一个内部提供的
