### ISSUE TITLE
生成国际化文件脚本

### ISSUE THREAD

**Issue by yvanwangl** [ant-design/intl-example#11]
npm run build:i18n-js

请问，这个脚本在什么地方，该怎么写呢？

**Comment by jaredleechn** [comment]
```
$ npm run trans
```
文档没有更新～

**Comment by yvanwangl** [comment]
我的开发使用的dva，
然后本地配置了l10n.config.js文件，按照文档进行的配置。
package.json配置如下：
{
  "name": "antd-intl-example",
  "private": true,
  "version": "1.0.0",
  "entry": {
    "en-US": "./src/entry/en-US.js",
    "zh-Hans-CN": "./src/entry/zh-Hans-CN.js",
    "index": "./src/entry/index.jsx"
  },
  "dependencies": {
    "antd": "1.0.x",
    "atool-build": "0.7.x",
    "babel-plugin-antd": "0.4.x",
    "react": "15.x",
    "react-dom": "15.x",
    "react-intl": "^2.0.0"
  },
  "devDependencies": {
    "atool-l10n": "^0.1.0",
    "babel-cli": "^6.4.0",
    "babel-eslint": "^6.0.0",
    "babel-plugin-react-intl": "^2.0.0",
    "babel-preset-es2015": "~6.6.0",
    "babel-preset-react": "~6.5.0",
    "babel-preset-stage-0": "~6.5.0",
    "dora": "0.3.x",
    "dora-plugin-hmr": "0.5.x",
    "dora-plugin-livereload": "0.3.x",
    "dora-plugin-proxy": "0.6.x",
    "dora-plugin-webpack": "0.6.x",
    "eslint": "^2.7.0",
    "eslint-config-airbnb": "6.x",
    "eslint-plugin-react": "4.x",
    "glob": "~7.0.3",
    "mkdirp": "~0.5.1",
    "pre-commit": "1.x",
    "rimraf": "^2.5.0"
  },
  "pre-commit": [
    "lint"
  ],
  "scripts": {
    "start": "npm run dev",
    "dev": "dora -p 8001 --plugins webpack,proxy,hmr,livereload",
    "lint": "eslint --ext .js,.jsx src",
    "build": "atool-build -o ./dist/${npm_package_name}/${npm_package_version}/",
    "trans": "atool-l10n"
  }
}

安装atool-l10n之后运行，npm run trans，打出如下log：
$ npm run trans

> @ trans E:\stariboss\agent-web\src\main\webapp
> atool-l10n

     atool-l10n: summary, fetchLocal, metaToResult, youdao, reduce, save
        summary: i18n-messages/**/*.json
        summary: no local files find, run webpack with babel-plugin-intl first
     fetchLocal: no local files need to be processed
   metaToResult: no element need to be processed
         youdao: no element need to be processed
         reduce: no element need to be processed
      save task: dest is locales

请问该如何解决呢？感谢

**Comment by jaredleechn** [comment]
> summary: no local files find, run webpack with babel-plugin-intl first

需要跑 build 或者 start 运行 webpack，将 babel-plugin-intl 扫描到的待翻译资源收集到 `i18n-messages` 下

可以开两个终端，一个一直跑 start，一个跑翻译

**Comment by yesmeck** [comment]
是 `babel-plugin-intl` 还是 `babel-plugin-react-intl` ？

**Comment by jaredleechn** [comment]
babel-plugin-react-intl

https://github.com/ant-design/intl-example/blob/master/package.json#L22

**Comment by yesmeck** [comment]
这里写的 `babel-plugin-intl` https://github.com/ant-tool/atool-l10n/blob/bbb9d793d375bc3edfebaaa642135a4fa8a2d29d/src/plugins/summary.js#L28
