### ISSUE TITLE
请问能够明确一下自动生成翻译资源文件的方法吗？

### ISSUE THREAD

**Issue by EscapeB** [ant-design/intl-example#15]
在文档中看到了用 npm run build:i18n-js 自动生成，但是我在项目中并没有看到。能麻烦详细描述一下吗

**Comment by jaredleechn** [comment]
文档没有同步更新，是 npm run trans，参考图

![image](https://camo.githubusercontent.com/62941884e925ec199427ee885fc2b7e6f1b4a777/68747470733a2f2f7a6f732e616c697061796f626a656374732e636f6d2f726d73706f7274616c2f4a6f474b686766754658614a4e7a4b2e676966)

**Comment by EscapeB** [comment]
感谢！
