### ISSUE TITLE
ant-design的Modal组件无法访问到react-intl的<IntlProvider> / ant-design Modal component does not work with react-intl <IntlProvider> component

### ISSUE THREAD

**Issue by ericxinzhang** [ant-design/intl-example#18]
我正在用dva，antdesign和react-intl框架开发一个单页应用程序，并且使用react-intl实现国际化。我在最外层的index.js用 `<IntlProvider>`将所有的组件都包裹起来，这样所有的子组件都能访问到intl对象。

I am building a SPA using dva, antdesign and react-intl. I enclosed all the other components with `<IntlProvider>` component from react-intl therefor all the children components have access to the intl object.

绝大部分页面和组件都工作正常，但是antdesign的Modal所显示的内容，用react-intl的`<FormattedMessage id="message.id"/>` 之后报错，错误信息是：`[React Intl] Could not find required intl object. <IntlProvider> needs to exist in the component ancestry.`

Most of the pages and components are working fine, however antdesign Modal cannot render the content after I changed the content to `<FormattedMessage id="message.id"/>`. The error message is: `[React Intl] Could not find required intl object. <IntlProvider> needs to exist in the component ancestry.`

我通过Chrome的React插件观察了组件的结构，出现此问题的原因是Model组件是写在最外面（和App平级的）的这样就不是`<IntlProvider>`的子组件了，请参见下图。

I inspected the page using Chrome React plugin, the reason was that Modal component is rendered at the top level, same level as the app.  Please refer to screen shot below.

![1285239407-5ba604c7b3b68_articlex](https://user-images.githubusercontent.com/2282738/45915672-47962d00-be9c-11e8-8522-c430d4cbf451.png)

一个解决办法是把所有使用到Modal的页面和组件再次引入语言包并用<IntlProvider>包裹一遍，不过这个办法貌似不太好，请问有什么更好的解决办法吗？谢谢！

A resolution is to import the React Intl's locale data and enclose the Modal content with <IntlProvider> for all the pages and components that use antdesign Modal, but I don't think it's a good idea. Any other suggestions are appreciated. Thanks!

**Comment by chenshuai2144** [comment]
使用 formatmessage 方法就好了

**Comment by ericxinzhang** [comment]
> 使用 formatmessage 方法就好了

谢谢! 我不熟react-intl
