### ISSUE TITLE
考虑 index.vm 支持

### ISSUE THREAD

**Issue by ChrisFan** [ant-design/intl-example#2]
目前生成了 index.html & index.en.html，但是这种方式意味着在访问 /index.html 时就已经决定了语言；  
在某些场景下，无法满足需求，比如我有两个系统 A、B，需求是：
1. 访问系统时根据浏览器判断默认语言
2. 再次访问系统时，需要保留上次选择的语言
3. A、B 系统切换时，语言要保持一致

于是，从实现上来说，我们会利用 cookie 存储上次选择的语言，并以此来达到多个系统间切换时保持语言一致的功能。

这个时候有两种做法：
1. 生成一个 index.html，在客户端判断语言后，异步获取语言包
2. 生成一个后端模版，比如 index.vm，里面包含语言包逻辑

@yiminghe @sorrycc 你们觉得呢？这种情况有什么好办不

**Comment by yiminghe** [comment]
不用管，后端自己根据 cookie 渲染不同的内容就行了
