### ISSUE TITLE
window下执行 npm run build:i18n-messages报错

### ISSUE THREAD

**Issue by pookpal** [ant-design/intl-example#6]
![image](https://cloud.githubusercontent.com/assets/10249353/17240688/8a9a8bd6-559f-11e6-8027-ca7275dc8ead.png)

**Comment by pookpal** [comment]
mac下没有问题

**Comment by jaredleechn** [comment]
依赖安装都 ok 么？

可以在 node_modules 下检查有没有 rimraf 和 babel 的文件

**Comment by pookpal** [comment]
依赖安装都没有问题，是window的package.json的配置问题，我已经解决了，脚本语句修改如下：
"build:i18n-messages": "rimraf i18n-messages && SET BABEL_ENV=i18n&&babel --quiet src > c:nul",
"build:i18n-js": "npm run build:i18n-messages && babel-node --presets es2015 scripts/translate.js"

**Comment by afc163** [comment]
`/dev/null` 是 Unix 系统才有的。

**Comment by pookpal** [comment]
偏右大神出现了呀~  恩  其实不知道为啥 设置babel环境变量后的那个 && 左右两边不能留空格，留空格就不能生效，除非分开执行

**Comment by pookpal** [comment]
@afc163 偏右大神，非常感谢你们，借鉴了你们的antd  antd-init，自己搞了个脚手架 ，没有依赖你们的atool-build，实现了，修改默认antd主题样式，css模块化，国际化等，项目地址https://github.com/pookpal/star-initReact

**Comment by jaredleechn** [comment]
get，这个 scripts 的确是有问题

这个例子比较旧了，这周末就会发布新的版本，支持本地化文件自动生成等等
